FROM phpmyadmin:5.2.2
COPY ./blueberry /var/www/html/themes/blueberry
COPY ./boodark-orange /var/www/html/themes/boodark-orange
RUN chown -R www-data:www-data /var/www/html/themes/blueberry
RUN chown -R www-data:www-data /var/www/html/themes/boodark-orange